this["__templates"] = this["__templates"] || {};
this["__templates"]["footer"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<footer role=\"contentinfo\" class=\"nav-footer\">\n    <div class=\"nav-bounds\">\n        <!-- Logged in content (small devices) -->\n        <p class=\"nav-footer-user\">Username (<a href=\"https://www.mercadolibre.com/jms/mla/lgz/logout\" rel=\"nofollow\">Salir</a>)</p>\n        <!-- Not logged in content (small devices) -->\n        <!--\n        <p class=\"nav-footer-user\">\n            <a class=\"nav-footer-registration ch-btn-skin ch-btn-small\" href=\"https://registration.mercadolibre.com.ar/registration/\" rel=\"nofollow\">Regístrate</a>\n            <a href=\"https://www.mercadolibre.com/jms/mla/lgz/login\" rel=\"nofollow\">Ingresa</a>\n        </p>\n        -->\n\n        <!-- Each country has different copyrights. Check which copyright you need. -->\n        <div class=\"nav-footer-primaryinfo\">\n            <small class=\"nav-footer-copyright\">© 1999-YYYY MercadoLibre</small>\n\n            <nav class=\"nav-footer-navigation\">\n                <a href=\"http://www.mercadolibre.com.ar/seguro_terminos.html\">Términos y condiciones</a>\n                <a href=\"http://www.mercadolibre.com.ar/seguro_privacidad.html\">Políticas de privacidad</a>\n                <a href=\"http://ayuda.mercadolibre.com.ar/\">Ayuda</a>\n            </nav>\n\n            <a href=\"#\" class=\"nav-footer-change-device\">Versión clásica</a>\n        </div>\n\n        <p class=\"nav-footer-secondaryinfo\">CNPJ n.º 03.007.331/0001-41 / Avenida Marte, 489, Térreo, Parte A / Santana de Parnaíba-SP / CEP: 06541-005 - empresa do grupo MercadoLivre.</p>\n    </div>\n</footer>\n";
  },"useData":true});
this["__templates"]["header"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<header role=\"banner\" class=\"nav-header nav-header-lite\">\n    <div class=\"nav-bounds\">\n        <a class=\"nav-logo\" href=\"/\" tabindex=\"1\">MercadoLibre - Donde compras y vendes de todo</a>\n        <!-- Menu - Switch checkbox (Small devices) -->\n        <input type=\"checkbox\" id=\"nav-header-menu-switch\"/>\n        <div class=\"nav-header-menu-wrapper\">\n            <!-- Menu - Hamburger (Small devices) -->\n            <label for=\"nav-header-menu-switch\" aria-controls=\"nav-header-menu\" data-fastClick tabindex=\"3\">\n                <i class=\"nav-header-menu-switch-icon\"></i>\n            </label>\n            <!-- Menu - Expandable (Logged in) -->\n            <nav id=\"nav-header-menu\">\n                <div class=\"nav-header-user\">\n                    <label for=\"nav-header-user-switch\" data-fastClick tabindex=\"4\">\n                        <!--[if lt IE 9]><a href=\"https://myaccount.mercadolibre.com.ar/summary/\" rel=\"nofollow\"><![endif]-->\n                        Username <i class=\"nav-icon-user\"></i>\n                        <!--[if lt IE 9]></a><![endif]-->\n                    </label>\n                    <input type=\"checkbox\" id=\"nav-header-user-switch\"/>\n                    <nav class=\"nav-header-user-layer\">\n                        <a href=\"https://myaccount.mercadolibre.com.ar/summary/\" rel=\"nofollow\">Mi cuenta</a>\n                        <a href=\"https://www.mercadolibre.com/jms/mla/lgz/logout\" rel=\"nofollow\">Salir</a>\n                    </nav>\n                </div>\n                <a href=\"http://ayuda.mercadolibre.com.ar/\"><i class=\"nav-icon-help\"><span>Ayuda</span></i></a>\n            </nav>\n        </div>\n    </div>\n</header>\n";
  },"useData":true});
this["__templates"]["shipping"] = this["__templates"]["shipping"] || {};
this["__templates"]["shipping"]["main"] = Handlebars.template({"1":function(depth0,helpers,partials,data) {
  return "    <li class=\"ch-form-row\" data-js=\"accord\">\n        <input type=\"radio\" name=\"shipping\" value=\"accord\" id=\"accordShipping\" />\n        <label for=\"accordShipping\">Lo acuerdo con el vendedor</label>\n    </li>\n";
  },"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, buffer = "<h2>Formas de entrega</h2>\n\n<ul class=\"ch-form-options\" data-js=\"shipping\">\n";
  stack1 = helpers['if'].call(depth0, ((stack1 = (depth0 != null ? depth0.preferences : depth0)) != null ? stack1.local_pick_up : stack1), {"name":"if","hash":{},"fn":this.program(1, data),"inverse":this.noop,"data":data});
  if (stack1 != null) { buffer += stack1; }
  return buffer + "\n    <li class=\"ch-form-row\" data-js=\"custom\">\n        <input type=\"radio\" name=\"shipping\" value=\"custom\" id=\"customShipping\" />\n        <label for=\"customShipping\">Envio a mi domicilio</label>\n    </li>\n</ul>\n";
},"useData":true});